export class TransactionEntity {}

export enum TRANSACTION_TYPE_ENUM {
  TOP_UP = 'TOP_UP',
  EXPANSES = 'EXPANSES',
  VAULT = 'VAULT',
  SUBSCRIPTION_EXPANSES = 'SUBSCRIPTION_EXPANSES',
  SUBSCRIPTION_INCOME = 'SUBSCRIPTION_INCOME',
  SUBSCRIPTION_PAYMENT = 'SUBSCRIPTION_PAYMENT',
}

export type TransactionType = keyof typeof TRANSACTION_TYPE_ENUM;
